### ISSUE TITLE
GitHub README显示格式问题。

### ISSUE THREAD

**Issue by Mirasire** [Foldblade/XUJC-thesis-markdown#1]
github不支持[toc]和$$符号的渲染。

**Comment by Foldblade** [comment]
感谢您的建议。

我的个人习惯是会保留 `[TOC]` 和 LaTeX 的语法，这样当用户克隆项目到本地、且采用支持此类语法的编辑器打开且阅读时，在渲染后可以有着更好的阅读体验。

仍然感谢您的建议，这提醒了我为文档站添加 LaTeX 语法的显示支持。
